name: LogGrabber
on:
  workflow_run:
    workflows: [SampleWorkflow, Manual Approval Workflow]
    types: [completed]
    branches: [main]
    
jobs:
  download:
    runs-on: self-hosted
    steps:
      - name: Fetch Payload
        uses: actions/github-script@v6
        with:
          script: |
           const payload = context.payload
           console.log("Printing Workflow_run")
           console.log(payload.workflow_run)
      - name: Ingest Log To Splunk
        uses: Yog4Prog/log-ingest-splunk-action@main
        with:
          repo: ${{ github.repository }}
          runId: ${{ github.event.workflow_run.id }}
          workflowName: ${{ github.event.workflow_run.name }}
          workflowPath: ${{ github.event.workflow_run.path }}
          headBranch: ${{ github.event.workflow_run.head_branch }}
          conclusion: ${{ github.event.workflow_run.conclusion }}
          gitToken: ${{ secrets.GIT_AUTH_TOKEN}}
          splunkUrl: 'https://localhost:8088'
          splunkHEC: ${{ secrets.SPLUNK_HEC_TOKEN }}
          
          
          
