name: LogGrabber
on:
  workflow_run:
    workflows: [SampleWorkflow]
    types: [completed]
    branches: [main]
    
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Payload
        uses: actions/github-script@v6
        with:
          script: |
           const payload = context.payload
           console.log(payload)
           console.log("Printing Workflow_run")
           console.log(payload.workflow_run)
       
 
