name: LogGrabber
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ApprovalWorkflow]
    types:
      - completed
jobs:
  download:
    runs-on: ubuntu-latest
    name: Download Logs
    steps:
      - name: Fetch Payload
      - uses: actions/github-script@v6
        with:
          script: |
           const payload = context.payload
           console.log(payload)
