on: [push]

jobs:
  create_approval_issue:
    runs-on: ubuntu-latest
    name: Create Approval Request 
    steps:
      - name: Creating an Issue for Approval
        id: ApprovalIssue
        uses: Yog4Prog/GatesApproval@main
        with:
          approvers: 'Yog4Prog'
          secret: ${{ secrets.AUTH_TOKEN }}
          owner: 'Yog4Prog'
          repo: 'GatesApproval'
          timeout: '2'
          issue_title: 'A Scan has a fialure.. Please approve to proceed'
          body_message: 'Found an Issue while performing SCA Scan'
          labels: 'bug'
