on: [push]

jobs:
  create_approval_issue:
    runs-on: ubuntu-latest
    name: Create Approval Request 
    steps:
      - name: Creating an Issue for Approval
        id: ApprovalIssue
        uses: Yog4Prog/GatesApproval@main
        with:
          approvers: 'Yog4Prog'
          secret: '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'
