name: Manual Approval Workflow
on: [workflow_dispatch]

jobs:
  
  Build:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Checkout Code
        id: Checkout
        uses: actions/checkout@v2.5.0
      - name: Compile Code
        run: echo "Code compilation completed."  
      - name: Run Unit Test
        run: echo "Unit Test execution completed"
  ScanCode:
    runs-on: ubuntu-latest
    needs: Build
    name: Quality Check ScanCode
    steps:
      - name: Sonar Inspect
        run: echo "Sonar Inspect completed"
  QualityGate:
    runs-on: ubuntu-latest
    needs: ScanCode
    name: Quality Gate A
    steps:
      - name: Gate(A) Check
        run: echo "Quality Check Gate(A) completed.."
  create_approval_issue:
    runs-on: ubuntu-latest
    needs: QualityGate
    name: Create Approval Request 
    steps:
      - name: Creating an Issue for Approval
        id: ApprovalIssue
        uses: Yog4Prog/GatesApproval@main
        with:
          owner: 'Yog4Prog'
          org: 'Yog4Prog'
          repo: 'GatesApproval'
          approvers: 'Yog4Prog'
          secret: ${{ secrets.AUTH_TOKEN }}
          timeout: '1'
          issue_title: 'A Scan has a failure.. Please approve to proceed'
          body_message: 'Found an Issue while performing SCA Scan'
          labels: 'ScanFailure'
